#!/bin/sh

[ $# -eq 0 ] && exit 1

cp -f Makefile "solutions/$1"
cp -f mosquito "solutions/$1"

cd "solutions/$1" || exit 1

echo 'bar baz' > "solutions/$1/foo"
echo 'dafuq' > "solutions/$1/wat"
echo 'quux abc' > "solutions/$1/baz"
