#!/bin/sh

echo 'preparing...'

err=0

compare()
{
    if cmp $2 $1.orig > /dev/null 2>&1
    then
        echo 'ok'
    else
        echo 'FAIL'
        err=$((err + 1))
    fi
}

echo 'bar baz' > foo
echo 'dafuq' > wat
echo 'quux abc' > baz

echo 'testing first task... '
./1 5 foo wat
compare 1 foo

echo 'testing second task... '
./2 abc ghi foo 2.out
compare 2 2.out

echo 'testing third task... '
./3 abc ghi foo baz > 3.out
compare 3 3.out

echo 'testing fourth task, first subtask... '
./4-1 Control mosquito > 4-1.out
compare 4-1 4-1.out

echo 'testing fourth task, second subtask... '
./4-2 grep end sort -r wc -l < mosquito > 4-2.out
compare 4-2 4-2.out
